// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfbmiUWOXlrP06ugoLBVV0yM76EdvEGIQ',
    appId: '1:637593383635:web:3a7cc3059698801e9a9a26',
    messagingSenderId: '637593383635',
    projectId: 'licitacoes-app',
    authDomain: 'licitacoes-app.firebaseapp.com',
    storageBucket: 'licitacoes-app.firebasestorage.app',
    measurementId: 'G-0LCEMH916G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJzxNE8AqDI7gDbEWOU5WNOIgKsTVzazg',
    appId: '1:637593383635:android:8ede371807dca2149a9a26',
    messagingSenderId: '637593383635',
    projectId: 'licitacoes-app',
    storageBucket: 'licitacoes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFnwx2h7FT5A_NuDGiF5ehWk739fj_Yb8',
    appId: '1:637593383635:ios:f4086350a7b5aad59a9a26',
    messagingSenderId: '637593383635',
    projectId: 'licitacoes-app',
    storageBucket: 'licitacoes-app.firebasestorage.app',
    androidClientId: '637593383635-jghbvv3kft1nio3qmsv2ltj5kfdqquo8.apps.googleusercontent.com',
    iosClientId: '637593383635-9588ke6bkh1uqvt3qhd991qnglbb7ksk.apps.googleusercontent.com',
    iosBundleId: 'com.example.acaoLicita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFnwx2h7FT5A_NuDGiF5ehWk739fj_Yb8',
    appId: '1:637593383635:ios:f4086350a7b5aad59a9a26',
    messagingSenderId: '637593383635',
    projectId: 'licitacoes-app',
    storageBucket: 'licitacoes-app.firebasestorage.app',
    androidClientId: '637593383635-jghbvv3kft1nio3qmsv2ltj5kfdqquo8.apps.googleusercontent.com',
    iosClientId: '637593383635-9588ke6bkh1uqvt3qhd991qnglbb7ksk.apps.googleusercontent.com',
    iosBundleId: 'com.example.acaoLicita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfbmiUWOXlrP06ugoLBVV0yM76EdvEGIQ',
    appId: '1:637593383635:web:73d76d98df13ed199a9a26',
    messagingSenderId: '637593383635',
    projectId: 'licitacoes-app',
    authDomain: 'licitacoes-app.firebaseapp.com',
    storageBucket: 'licitacoes-app.firebasestorage.app',
    measurementId: 'G-PLC7J748RE',
  );
}
